import type { Metadata } from "next";
import "@/styles/globals.scss";
import "./globals.css";

export const metadata: Metadata = {
  title: "Smart Search",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="en" data-theme="light">
      <body className={"antialiased"}>{children}</body>
    </html>
  );
};

export default RootLayout;
